word_list = [
    'anı',
    'absürt',
    'Uçurum',
    'takım',
    'çarpık',
    'Bulvar',
    'garip',
    'aksiyon',
    'masmavi',
    'gayda',
    'çoğunluk',
    'banyo',
    'bayou',
    'arıcı',
    'bikini',
    'yıldırım',
    'kar fırtınası',
    'boğaz',
    'kitap kurdu',
    'şarbon',
    'kutu',
    'karabiber',
    'bufalo',
    'soytarı',
    'dolgun',
    'şahin',
    'uğultu',
    'kelimeler',
    'halife',
    'örümcek ağı',
    'ukalalık',
    'kroket',
    'mezar odası',
    'Curacao',
    'Çeviri',
    'reddetmek',
    'baş dönmesi',
    'dubleks',
    'cüceler',
    'zinnet',
    'donatmak',
    'casusluk',
    'çıkış',
    'sahte',
    'olta',
    'düzeltilebilir',
    'fiyort',
    'çırpıcı',
    'kayma',
    'kabarık',
    'uçuş',
    'yüksükotu',
    'çarpık',
    'kıvırcık',
    'fuşya',
    'eğlenceli',
    'gökada',
    'galvaniz',
    'çardak',
    'gavur',
    'Budaklı',
    'dedikodu',
    'sarhoşluk',
    'haki',
    'gelişigüzel',
    'titremek',
    'iyatrojenik',
    'buzluk',
    'incinme',
    'fildişi',
    'sarmaşık',
    'ikramiye',
    'sarılık',
    'çene',
    'dikkatsizce',
    'jöle',
    'yapboz',
    'uğursuzluk',
    'jokey',
    'hafif koşu',
    'şaka',
    'neşeli',
    'neşe dolu',
    'sulu',
    'müzik kutusu',
    'büyük',
    'kayık',
    'kazo',
    'anahtar deliği',
    'haki',
    'kilobayt',
    'köşk',
    'kivi meyvesi',
    'klutz',
    'sırt çantası',
    'gırtlak',
    'uzunluk',
    'şanslı',
    'lüks',
    'lenf',
    'marki',
    'matris',
    'megahertz',
    'mikrodalga',
    'anımsatıcı',
    'gizlemek',
    'nafta',
    'gece kulübü',
    'bu günlerde',
    'mankafa',
    'perisi',
    'oniks',
    'yumurtalık',
    'oksitlemek',
    'oksijen',
    'pijama',
    'peekabu',
    'balgam',
    'piksel',
    'pizza',
    'Zatürre',
    'polka',
    'ruh',
    'köpek yavrusu',
    'şaşırtıcı',
    'kuvars',
    'sıra',
    'şaka',
    'kişot',
    'sınav',
    'çoğunluk',
    'ritim',
    'çekçek',
    'kaşımak',
    'şiv',
    'şık',
    'sfenks',
    'cıvıldamak',
    'Personel',
    'kuvvet',
    'güçlü',
    'uzatmak',
    'kale',
    'bıyık',
    'metro',
    'döner',
    'sendrom',
    'tasarrufsuz',
    'parmak vidası',
    'topaz',
    'ihlal',
    'nakil',
    'on ikinci',
    'oniki',
    'Bilinmeyen',
    'değersiz',
    'aç',
    'şehir dışı',
    'buharlaştırmak',
    'canavar',
    'votka',
    'vudu',
    'girdap',
    'röntgencilik',
    'geçit',
    'vals',
    'dalga',
    'dalgalı',
    'mumsu',
    'kaynak',
    'hırıltılı',
    'viski',
    'vızıltı',
    'kimse',
    'püskül',
    'cadılık',
    'sihirbaz',
    'sersem',
    'kol saati',
    'yavru',
    'ksilofon',
    'yok',
    'genç',
    'lezzetli',
    'zefir',
    'zikzaklı',
    'zikzak',
    'zilç',
    'fermuar',
    'zodyak',
    'zombi',
]
